spring:
  application:
    name: sample-rest-service
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
    hikari:
      connection-timeout: 2000
      initialization-fail-timeout: 0
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        enable_lazy_load_no_trans: true

management:
  endpoints:
    web:
      exposure:
        include: httptrace, health, metrics, info

server:
  port: 8080

logging:
  level:
    root: WARN
    com.murali.rest: TRACE